[package]
name = "gawserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
surrealdb = { version = "2.2.0", features = ["kv-rocksdb","kv-mem"] }
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
